Repository palantir/log4j-sniffer, pull requests merged in 2021-12, with the labels that each got.

#6 improvement: Publish darwin-arm64 binaries
  README.md
  changelog/@unreleased/pr-6.v2.yml
  godel/config/dist-plugin.yml
Labels: merge when ready, autorelease

#9 Update README
  README.md
Labels: no changelog, merge when ready

#13 Add note about suffix matching
  README.md
Labels: no changelog, merge when ready

#12 improvement: Do not emit metric logs
  README.md
  changelog/@unreleased/pr-12.v2.yml
  cmd/context.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/context.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/default.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/logger.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/logger_default.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/logger_wrapped.go
  vendor/github.com/palantir/witchcraft-go-logging/wlog/evtlog/evt2log/params.go
  vendor/modules.txt
Labels: merge when ready

#14 Minor improvements and fixes to comments
  pkg/archive/paths.go
  pkg/crawl/crawler.go
Labels: no changelog

#18 Correct ignore-dir help text
  changelog/@unreleased/pr-18.v2.yml
  cmd/crawl.go
Labels: merge when ready

#21 Build windows binaries
  changelog/@unreleased/pr-21.v2.yml
  godel/config/dist-plugin.yml
Labels: merge when ready

#22 Add readme note about windows binaries
  README.md
Labels: no changelog, merge when ready

#25 Second CVE
  README.md
  changelog/@unreleased/pr-25.v2.yml
  cmd/crawl.go
  examples/cve-2021-45105-versions/log4j-core-2.12.2.jar
  examples/cve-2021-45105-versions/log4j-core-2.16.0.jar
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
  pkg/crawl/report.go
Labels: merge when ready, autorelease

#26 Fix readme typo
  README.md
Labels: no changelog, merge when ready

#27 Compare bytecode hashes
  README.md
  changelog/@unreleased/pr-27.v2.yml
  cmd/bytecode.go
  integration_test/crawl_integration_test.go
  pkg/crawl/identify.go
  pkg/crawl/report.go
  pkg/java/class.go
  pkg/java/jar.go
Labels: autorelease

#31 Specific file checks for tar vs zip
  changelog/@unreleased/pr-31.v2.yml
  pkg/crawl/identify.go
Labels: merge when ready

#24 Add support for recursing into zip files
  README.md
  changelog/@unreleased/pr-24.v2.yml
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/archive/paths.go
  pkg/archive/paths_test.go
  pkg/archive/zip.go
  pkg/archive/zip_test.go
  pkg/buffer/error.go
  pkg/buffer/sizelimited.go
  pkg/buffer/sizelimited_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#37 Reshape lookForMatchInFileInZip function
  pkg/crawl/identify.go
Labels: no changelog, merge when ready

#32 Add command to compare two classes
  changelog/@unreleased/pr-32.v2.yml
  cmd/compare.go
  cmd/identify.go
  cmd/root.go
  examples/obfuscated/2.14.1-aaaagb.jar
  integration_test/comparison_integration_test.go
  pkg/java/class.go
  pkg/java/comparison.go
  pkg/java/comparison_test.go
  pkg/java/jar.go
  pkg/java/opcodes.go
Labels: merge when ready

#43 Add support for uncompressed and bzip2 tar archives
  README.md
  changelog/@unreleased/pr-43.v2.yml
  examples/generate.sh
  examples/inside_a_dist/wrapped_log4j.tar
  examples/inside_a_dist/wrapped_log4j.tar.bz2
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/archive/formats.go
  pkg/archive/formats_test.go
  pkg/archive/paths.go
  pkg/archive/paths_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#38 Remove parent from lookForMatchInZip
  pkg/crawl/identify.go
Labels: no changelog, merge when ready

#44 Add configurable rate limiting for directories and archives.
  changelog/@unreleased/pr-44.v2.yml
  cmd/crawl.go
  go.mod
  go.sum
  internal/crawler/crawl.go
  pkg/crawl/crawler.go
  pkg/crawl/crawler_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
  vendor/github.com/andres-erbsen/clock/.travis.yml
  vendor/github.com/andres-erbsen/clock/LICENSE
  vendor/github.com/andres-erbsen/clock/README.md
  vendor/github.com/andres-erbsen/clock/clock.go
  vendor/go.uber.org/ratelimit/.gitignore
  vendor/go.uber.org/ratelimit/CHANGELOG.md
  vendor/go.uber.org/ratelimit/LICENSE
  vendor/go.uber.org/ratelimit/Makefile
  vendor/go.uber.org/ratelimit/README.md
  vendor/go.uber.org/ratelimit/go.mod
  vendor/go.uber.org/ratelimit/go.sum
  vendor/go.uber.org/ratelimit/limiter_atomic.go
  vendor/go.uber.org/ratelimit/limiter_mutexbased.go
  vendor/go.uber.org/ratelimit/ratelimit.go
  vendor/modules.txt
Labels: merge when ready

#36 Partial bytecode comparison during identify
  changelog/@unreleased/pr-36.v2.yml
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  pkg/crawl/class_hash.go
  pkg/crawl/identify.go
  pkg/crawl/report.go
  pkg/crawl/signatures.go
  pkg/java/comparison.go
  pkg/java/jar.go
Labels: merge when ready

#45 More reporting output
  changelog/@unreleased/pr-45.v2.yml
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/crawl/class_hash.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
  pkg/crawl/report.go
  pkg/crawl/report_test.go
Labels: merge when ready

#48 Remove unused metric-schema artifacts
  godel/config/metric-schema-plugin.yml
  metrics/metrics.yml
Labels: no changelog, merge when ready

#47 Support recursion across all archive types
  changelog/@unreleased/pr-47.v2.yml
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/archive/formats.go
  pkg/archive/paths.go
  pkg/archive/paths_test.go
  pkg/archive/walkers.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#49 Readme
  README.md
  cmd/crawl.go
  mac_download.png
Labels: no changelog, merge when ready

#51 Update readme
  README.md
Labels: no changelog, merge when ready

#52 Fix Markdown link
  README.md
Labels: no changelog, merge when ready
