Repository palantir/log4j-sniffer, pull requests merged in 2022-01, with the labels that each got.

#54 Add support for new versions introduced to address CVE-2021-44832
  README.md
  changelog/@unreleased/pr-54.v2.yml
  cmd/crawl.go
  examples/cve-2021-44832-versions/log4j-core-2.12.3.jar
  examples/cve-2021-44832-versions/log4j-core-2.17.0.jar
  examples/cve-2021-44832-versions/log4j-core-2.3.1.jar
  examples/good_version/log4j-core-2.12.4.jar
  examples/good_version/log4j-core-2.17.1.jar
  examples/good_version/log4j-core-2.3.2.jar
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
  pkg/crawl/report.go
  pkg/crawl/signatures.go
Labels: autorelease

#56 Updating Windows Instructions
  README.md
Labels: no changelog, merge when ready

#57 Add "--file-path-only" flag that prints only paths of files with CVEs
  changelog/@unreleased/pr-57.v2.yml
  cmd/crawl.go
  internal/crawler/crawl.go
  pkg/crawl/report.go
  pkg/crawl/report_test.go
Labels: merge when ready

#58 Fix "--disable-flagging-jndi-lookup" flag
  changelog/@unreleased/pr-58.v2.yml
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  pkg/crawl/report.go
Labels: merge when ready

#59 Add "--disable-unknown-versions" flag
  changelog/@unreleased/pr-59.v2.yml
  cmd/crawl.go
  internal/crawler/crawl.go
  pkg/crawl/report.go
  pkg/crawl/report_test.go
Labels: merge when ready

#60 Update README.md with new command-line options
  README.md
Labels: no changelog, merge when ready, autorelease

#61 Correct bytecode match flag name
  README.md
Labels: no changelog, merge when ready

#62 Only print walk error when not nil
  changelog/@unreleased/pr-62.v2.yml
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#66 build linux-arm64 binaries
  changelog/@unreleased/pr-66.v2.yml
  godel/config/dist-plugin.yml
Labels: merge when ready

#64 Do not exit with an error if maximum archive size exceeded
  changelog/@unreleased/pr-64.v2.yml
  examples/generate.sh
  examples/nested_very_deep/nested_thrice.tar.gz
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  pkg/archive/zip.go
  pkg/archive/zip_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#67 Remove wrapped error message
  pkg/archive/zip.go
Labels: no changelog, merge when ready

#68 Check for archive support before comparing size
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: no changelog, merge when ready

#65 Print skipped paths
  README.md
  changelog/@unreleased/pr-65.v2.yml
  internal/crawler/crawl.go
  pkg/crawl/crawler.go
  pkg/crawl/crawler_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready, autorelease

#74 Correctly use exact match signatures in partial matching
  changelog/@unreleased/pr-74.v2.yml
  pkg/crawl/signatures.go
Labels: merge when ready

#75 Fix some nits before larger PR
  pkg/crawl/crawler.go
  pkg/crawl/crawler_test.go
  pkg/crawl/identify.go
  pkg/crawl/report.go
  pkg/crawl/report_test.go
Labels: no changelog, merge when ready

#76 Accept ProcessFunc into top-level Crawl function
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
Labels: no changelog, merge when ready

#79 Skip all class-based checks when not .class
  pkg/crawl/identify.go
Labels: no changelog

#80 Match JndiManager classes with a renamed file extension
  changelog/@unreleased/pr-80.v2.yml
  examples/generate.sh
  examples/renamed_jar_class_file_extensions/not-a-finding.jar
  examples/renamed_jar_class_file_extensions/renamed-log4j-class.jar
  integration_test/crawl_integration_test.go
  internal/crawler/crawl_test.go
  pkg/crawl/identify.go
Labels: merge when ready

#82 Optionally trace log path when crawling
  README.md
  changelog/@unreleased/pr-82.v2.yml
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  pkg/crawl/identify.go
Labels: merge when ready, autorelease

#83 Evalaute obfuscation for each class individually rather than averaging a whole jar
  changelog/@unreleased/pr-83.v2.yml
  cmd/crawl.go
  integration_test/crawl_integration_test.go
  internal/crawler/crawl.go
  internal/crawler/crawl_test.go
  pkg/crawl/identify.go
  pkg/java/jar.go
Labels: merge when ready

#87 Implement memory considerate zip walker
  LICENSE
  changelog/@unreleased/pr-87.v2.yml
  godel/config/check-plugin.yml
  godel/config/license-plugin.yml
  pkg/archive/walkers.go
  pkg/archive/zip.go
  pkg/archive/zip/README.md
  pkg/archive/zip/reader.go
  pkg/archive/zip/reader_local_test.go
  pkg/archive/zip/reader_test.go
  pkg/archive/zip/register.go
  pkg/archive/zip/struct.go
  pkg/archive/zip/testdata/crc32-not-streamed.zip
  pkg/archive/zip/testdata/dd.zip
  pkg/archive/zip/testdata/go-no-datadesc-sig.zip.base64
  pkg/archive/zip/testdata/go-with-datadesc-sig.zip
  pkg/archive/zip/testdata/gophercolor16x16.png
  pkg/archive/zip/testdata/large-number-of-files.zip
  pkg/archive/zip/testdata/readme.notzip
  pkg/archive/zip/testdata/readme.zip
  pkg/archive/zip/testdata/single-file.zip
  pkg/archive/zip/testdata/subdir.zip
  pkg/archive/zip/testdata/symlink.zip
  pkg/archive/zip/testdata/test-trailing-junk.zip
  pkg/archive/zip/testdata/test.zip
  pkg/archive/zip/testdata/time-22738.zip
  pkg/archive/zip/testdata/time-7zip.zip
  pkg/archive/zip/testdata/time-go.zip
  pkg/archive/zip/testdata/time-infozip.zip
  pkg/archive/zip/testdata/time-osx.zip
  pkg/archive/zip/testdata/time-win7.zip
  pkg/archive/zip/testdata/time-winrar.zip
  pkg/archive/zip/testdata/time-winzip.zip
  pkg/archive/zip/testdata/two-files-with-subdirs.zip
  pkg/archive/zip/testdata/unix.zip
  pkg/archive/zip/testdata/utf8-7zip.zip
  pkg/archive/zip/testdata/utf8-infozip.zip
  pkg/archive/zip/testdata/utf8-osx.zip
  pkg/archive/zip/testdata/utf8-winrar.zip
  pkg/archive/zip/testdata/utf8-winzip.zip
  pkg/archive/zip/testdata/winxp.zip
  pkg/archive/zip/testdata/zip64-2.zip
  pkg/archive/zip/testdata/zip64.zip
  pkg/archive/zip/walk.go
  pkg/archive/zip/writer.go
  pkg/archive/zip/zip_test.go
  pkg/archive/zip_test.go
Labels: merge when ready, autorelease

#88 Use a bounded amount of memory per directory
  changelog/@unreleased/pr-88.v2.yml
  internal/crawler/crawl.go
  pkg/crawl/crawler.go
  pkg/crawl/crawler_test.go
  pkg/crawl/identify.go
  pkg/crawl/identify_test.go
Labels: merge when ready

#89 Extract crawl flags and logger
  cmd/crawl.go
  cmd/flags.go
  internal/crawler/crawl.go
  pkg/crawl/identify.go
  pkg/crawl/path.go
  pkg/crawl/report.go
  pkg/log/logger.go
Labels: no changelog, merge when ready
